
#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();

cout<<"\n  _______ ";
cout<<"\n--'   ____) ";
cout<<"\n     (_____) ";
cout<<"\n     (_____) ";
cout<<"\n     (____) ";
cout<<"\n---.__(___) ";

 cout<<"\n\n\n\n";


 cout<<"\n     _______ ";
 cout<<"\n---'    ____)____";
 cout<<"\n           ______) ";
 cout<<"\n          _______) ";
 cout<<"\n         _______) ";
 cout<<"\n---.__________) ";

 cout<<"\n\n\n\n";


 cout<<"\n    _______ ";
 cout<<"\n---'   ____)____ ";
 cout<<"\n          ______) ";
 cout<<"\n       __________) ";
 cout<<"\n      (____) ";
 cout<<"\n---.__(___) ";
 
getch();
}